// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqosHOCBfNdne-d9-SWXGxaTGPzUNHP34',
    appId: '1:922575611847:web:dd35b42f722a257079dbe2',
    messagingSenderId: '922575611847',
    projectId: 'evently-app-clean',
    authDomain: 'evently-app-clean.firebaseapp.com',
    storageBucket: 'evently-app-clean.firebasestorage.app',
    measurementId: 'G-J6DHCG076P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTWlR28gZbMiw1rGvWA6ivFl_FsHGN2dE',
    appId: '1:922575611847:android:e1ffcfad753449a679dbe2',
    messagingSenderId: '922575611847',
    projectId: 'evently-app-clean',
    storageBucket: 'evently-app-clean.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqU2VDFKsRo8KzaEbyD7jh4nVgHmhBMDw',
    appId: '1:922575611847:ios:9f45d9c1bd3ed24b79dbe2',
    messagingSenderId: '922575611847',
    projectId: 'evently-app-clean',
    storageBucket: 'evently-app-clean.firebasestorage.app',
    androidClientId: '922575611847-ersknr6581j2op8cq6bugk7fqp3lu62f.apps.googleusercontent.com',
    iosClientId: '922575611847-58581l6gujgfut6o2epq36506jomq5ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqU2VDFKsRo8KzaEbyD7jh4nVgHmhBMDw',
    appId: '1:922575611847:ios:9f45d9c1bd3ed24b79dbe2',
    messagingSenderId: '922575611847',
    projectId: 'evently-app-clean',
    storageBucket: 'evently-app-clean.firebasestorage.app',
    androidClientId: '922575611847-ersknr6581j2op8cq6bugk7fqp3lu62f.apps.googleusercontent.com',
    iosClientId: '922575611847-58581l6gujgfut6o2epq36506jomq5ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqosHOCBfNdne-d9-SWXGxaTGPzUNHP34',
    appId: '1:922575611847:web:4cbd96ec6d03380a79dbe2',
    messagingSenderId: '922575611847',
    projectId: 'evently-app-clean',
    authDomain: 'evently-app-clean.firebaseapp.com',
    storageBucket: 'evently-app-clean.firebasestorage.app',
    measurementId: 'G-R1BVBYHGWZ',
  );

}